//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaroctoOCT.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=192.168.168.131;user id=pegasususer;database=varoctooct;pwd=pegasus;persis" +
            "tsecurityinfo=True")]
        public string varoctooctConnectionString {
            get {
                return ((string)(this["varoctooctConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int TextBoxMaxLength {
            get {
                return ((int)(this["TextBoxMaxLength"]));
            }
            set {
                this["TextBoxMaxLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\PegasusData")]
        public string ImageRootFolder {
            get {
                return ((string)(this["ImageRootFolder"]));
            }
            set {
                this["ImageRootFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pegasus4")]
        public string dDeviceID {
            get {
                return ((string)(this["dDeviceID"]));
            }
            set {
                this["dDeviceID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public long lLocationID {
            get {
                return ((long)(this["lLocationID"]));
            }
            set {
                this["lLocationID"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=192.168.168.131;user id=pegasususer;database=varoctooct;persistsecurityinf" +
            "o=True;allowuservariables=True")]
        public string varoctooctConnectionString2 {
            get {
                return ((string)(this["varoctooctConnectionString2"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double FixationRectangleHorizontalPixelsPerMm {
            get {
                return ((double)(this["FixationRectangleHorizontalPixelsPerMm"]));
            }
            set {
                this["FixationRectangleHorizontalPixelsPerMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double FixationRectangleVerticalPixelsPerMm {
            get {
                return ((double)(this["FixationRectangleVerticalPixelsPerMm"]));
            }
            set {
                this["FixationRectangleVerticalPixelsPerMm"] = value;
            }
        }
    }
}
